name: build and test allure-pytest

on:
  pull_request:
    branches:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install packages
        run: pip install build &&
             python -m build allure-python-commons &&
             python -m build allure-python-commons-test &&
             pip install allure-python-commons*/dist/allure-python-commons*.tar.gz &&
             pip install ./allure-pytest &&
             pip install -r allure-pytest/requirements.txt

      - name: Static check allure-pytest
        working-directory: allure-pytest
        run: flake8 src/ test/

  build:
    runs-on: ubuntu-latest
    needs: [linters]
    strategy:
      matrix:
        python-version: ["3.10", 3.9, 3.8, 3.7]
    env:
      ALLURE_INDENT_OUTPUT: yep
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: pip install build &&
             python -m build allure-python-commons &&
             python -m build allure-python-commons-test &&
             pip install allure-python-commons*/dist/allure-python-commons*.tar.gz &&
             pip install ./allure-pytest &&
             pip install -r allure-pytest/requirements.txt

      - name: Test allure-python
        working-directory: allure-pytest
        run: pytest --alluredir=allure-results --basetemp=tmp
              test/acceptance test/integration
